### ISSUE TITLE
Version 2.0.x not backwards compatible?

### ISSUE THREAD

**Issue by hcl-dr** [data-respons-solutions/nvram#2]
Updating from  a44eb31d96c8ed33b49717a5292c8509dc02f6c0 to HEAD will not display variable added with earlier version.
Revering back shows variable still there.

**Comment by ninjafinne** [comment]
Major version 2 broke backwards compatibility with an updated data header. Purpose of the update was to future proof header and allow adding features without breaking deployed systems.

The decision to break backwards compatibility was made lightly as no (?) systems were using the v1 header in production. 

Is this a problem?

**Comment by hcl-dr** [comment]
All good then.

**Comment by hcl-dr** [comment]
Closing as the change in header was ment to solve this kind of issues.
